name: buildReact

on: 
  push:
    branches: "main"
  workflow_dispatch:
    
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: installAndBuild
        run: |
          npm ci
          npm run build
          echo "BACKEND_API_URL: $({vars.VITE_BACKEND_API_URL})"

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
    
