name: buildReact

on: 
  push:
    branches: "main"
  workflow_dispatch:
    
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      
    steps:
      - uses: actions/checkout@v4.1.1

      - name: installAndBuild
        run: |
          npm ci
          npm run build
